### ISSUE TITLE
Not sure where I messed up, but my shit is broken

### ISSUE THREAD

**Issue by Tymec** [vsailev/ot-ma-ku#1]
The login page doesn't exist and the style is broken as well.
![.](https://i.gyazo.com/1875f593c3a75e7a3d2fdf0b53338d0d.gif)

**Comment by vsailev** [comment]
Can you specify the url of the login ?
As for the broken style compiling the assets is breaking it so for now I remove it from steps

**Comment by Tymec** [comment]
The url is <IP>/login

**Comment by vsailev** [comment]
and your main url is ?

**Comment by Tymec** [comment]
My main url is localhost
Not sure if I forgot to edit something in the .env file related to the login page

**Comment by vsailev** [comment]
You have to edit app/app.php:
'url' => env('APP_URL', 'http://localhost'),
with the url where your project is located and add public if you are not using artisan serve
for example
'url' => env('APP_URL', 'http://localhost/otmaku/public'),

**Comment by Tymec** [comment]
The project is located at localhost though.

**Comment by vsailev** [comment]
then change it to 'url' => env('APP_URL', 'http://localhost/public'),
and you access the site via localhost/public

**Comment by Tymec** [comment]
'Website not found'
Guess I messed up somewhere else.

**Comment by vsailev** [comment]
I don't know exactly your env or why it gives you that but can you restart over

**Comment by Tymec** [comment]
Ye, I'll try to do it over again.
